lines = []
lines.append("# -*- coding: utf-8 -*-")
lines.append("import sys, os, re, shutil, tempfile")
lines.append('if hasattr(sys.stdout, "reconfigure"):')
lines.append('    sys.stdout.reconfigure(encoding="utf-8")')
lines.append("try:")
lines.append('    from docx import Document')
lines.append("    from docx.oxml.ns import qn")
lines.append("    from docx.oxml import OxmlElement")
lines.append("    from docx.shared import Pt")
lines.append("except ImportError:")
lines.append('    print("ERROR: python-docx not installed", file=sys.stderr)')
lines.append("    sys.exit(1)")
lines.append('')
lines.append('NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"')
lines.append('')
lines.append('')
lines.append('def find_text(el):')
lines.append('    return "".join(t.text or "" for t in el.findall(f".//{{{NS}}}t"))')
lines.append('')
lines.append('def clear_para(p):')
lines.append('    for t in p.findall(f".//{{{NS}}}t"):')
lines.append('        t.text = ""')
lines.append('')
lines.append('def add_run(par, text, bold=False, size=10.5):')
lines.append('    r = OxmlElement("w:r")')
lines.append('    if bold:')
lines.append('        rPr = OxmlElement("w:rPr")')
lines.append('        rPr.append(OxmlElement("w:b"))')
lines.append('        r.append(rPr)')
lines.append('    t = OxmlElement("w:t")')
lines.append('    t.text = text')
lines.append('    t.set(qn("xml:space"), "preserve")')
lines.append('    r.append(t)')
lines.append('    par.append(r)')
lines.append('')
lines.append('def set_cell(cell, text, bold=False, size=10.5):')
lines.append('    paras = cell._element.findall(f".://{NS}}}p")')
lines.append('    if not paras:')
lines.append('        p = OxmlElement("w:p")')
lines.append('        cell._element.append(p)')
lines.append('        paras = [p]')
lines.append('    clear_para(paras[0])')
lines.append('    add_run(paras[0], text, bold=bold, size=size)')
lines.append('')
lines.append('')
lines.append('def parse_md(path):')
lines.append('    with open(path, encoding="utf-8") as f:')
lines.append('        text = f.read()')
lines.append('    d = dict(name="", contact="", intent="", summary="",')
lines.append('             edu_school="", edu_major="", edu_degree="", edu_dates="",')
lines.append('             courses="", honors="",')
lines.append('             projects=[], practices=[], campus=[], skills=[])')
lines.append('    section = None')
lines.append('    item = None')
lines.append('    for line in text.split("\\n"):')
lines.append('        s = line.strip()')
lines.append('        if not s:')
lines.append('            continue')
lines.append('        if s.startswith("# "):')
lines.append('            d["name"] = s[2:].strip()')
lines.append('        elif re.match(r"^\\*\\*求职意向\\*\\*[：:]", s):')
lines.append('            d["intent"] = re.sub(r"\\*\\*求职意向\\*\\*[：:]", "", s).strip()')
lines.append('        elif re.match(r"^\\*\\*个人优势\\*\\*[：:]", s):')
lines.append('            d["summary"] = re.sub(r"\\*\\*个人优势\\*\\*[：:]", "", s).strip()')
lines.append('        elif ("｜" in s or "|" in s) and not s.startswith("**") and not d["contact"]:')
lines.append('            d["contact"] = s')
lines.append('        elif s == "## 教育背景":')
lines.append('            section = "edu"')
lines.append('        elif s == "## 项目经历":')
lines.append('            section = "projects"')
lines.append('        elif s == "## 实践经历":')
lines.append('            section = "practices"')
lines.append('        elif s == "## 校园经历":')
lines.append('            section = "campus"')
lines.append('        elif s == "## 综合技能":')
lines.append('            section = "skills"')
lines.append('        elif section == "edu":')
lines.append('            if "**" in s and "｜" in s:')
lines.append('                parts = s.split("｜")')
lines.append('                if len(parts) >= 3:')
lines.append('                    d["edu_school"] = parts[0].replace("**", "").strip()')
lines.append('                    d["edu_major"] = parts[1].strip()')
lines.append('                    d["edu_degree"] = ""')
lines.append('                    d["edu_dates"] = parts[2].replace("**", "").strip()')
lines.append('                elif len(parts) == 2:')
lines.append('                    d["edu_school"] = parts[0].replace("**", "").strip()')
lines.append('                    d["edu_major"] = parts[1].replace("**", "").strip()')
lines.append('            elif "核心课程" in s:')
lines.append('                d["courses"] = re.sub(r"^\\*\\*[^*]*\\*\\*[：:]\\s*", "", s).strip()')
lines.append('            elif "荣誉奖励" in s:')
lines.append('                d["honors"] = re.sub(r"^\\*\\*[^*]*\\*\\*[：:]\\s*", "", s).strip()')
lines.append('        elif s.startswith("### "):')
lines.append('            if section in ("projects", "practices", "campus"):')
lines.append('                item = dict(title=s[4:].strip(), role="", dates="", bullets=[])')
lines.append('                d[section].append(item)')
lines.append('        elif s.startswith("**") and ("｜" in s or "|" in s) and item is not None:')
lines.append('            parts = s.split("｜")')
lines.append('            if len(parts) >= 2:')
lines.append('                item["role"] = parts[0].replace("**", "").strip()')
lines.append('                item["dates"] = parts[1].replace("**", "").strip()')
lines.append('        elif s.startswith("- ") and item is not None:')
lines.append('            item["bullets"].append(s[2:].strip())')
lines.append('        elif section == "skills" and s.startswith("- "):')
lines.append('            d["skills"].append(s[2:].strip())')
lines.append('    return d')
lines.append('')
lines.append('')
lines.append('def update_header(doc, d):')
lines.append('    tbl = doc.tables[0]')
lines.append('    set_cell(tbl.rows[0].cells[0], d["name"], bold=True, size=14)')
lines.append('    set_cell(tbl.rows[1].cells[0], d["contact"], size=9)')
lines.append('    if d["intent"]:')
lines.append('        set_cell(tbl.rows[2].cells[0], "求职意向：" + d["intent"], size=10)')
lines.append('    if d["summary"]:')
lines.append('        set_cell(tbl.rows[3].cells[0], "个人优势：" + d["summary"], size=9)')
lines.append('')
lines.append('')
lines.append('def update_edu(doc, d):')
lines.append('    tbl = doc.tables[1]')
lines.append('    for row in tbl.rows[1:]:')
lines.append('        for c in row.cells:')
lines.append('            for p in c._element.findall(f".://{NS}}}p"):')
lines.append('                clear_para(p)')
lines.append('    cells = tbl.rows[1].cells')
lines.append('    if len(cells) >= 1:')
lines.append('        set_cell(cells[0], d["edu_school"], bold=True, size=11)')
lines.append('    if len(cells) >= 2:')
lines.append('        set_cell(cells[1], d["edu_major"], size=10.5)')
lines.append('    if len(cells) >= 3:')
lines.append('        set_cell(cells[2], d["edu_degree"], size=10.5)')
lines.append('    if len(cells) >= 4:')
lines.append('        set_cell(cells[3], d["edu_dates"], size=10.5)')
lines.append('    tbl2 = doc.tables[2]')
lines.append('    cells = tbl2.rows[0].cells')
lines.append('    if d["courses"] and len(cells) > 0:')
lines.append('        set_cell(cells[0], "核心课程：" + d["courses"], size=9.5)')
lines.append('    if d["honors"] and len(cells) > 1:')
lines.append('        set_cell(cells[1], "荣誉奖励：" + d["honors"], size=9.5)')
lines.append('')
lines.append('')
lines.append('def update_section(doc, tidx, items, kwds):')
lines.append('    tbl = doc.tables[tidx]')
lines.append('    hi = None')
lines.append('    for i, row in enumerate(tbl.rows):')
lines.append('        for c in row.cells:')
lines.append('            txt = find_text(c._element)')
lines.append('            if any(k in txt for k in kwds):')
lines.append('                hi = i')
lines.append('                break')
lines.append('        if hi is not None:')
lines.append('            break')
lines.append('    if hi is None:')
lines.append('        return')
lines.append('    for row in tbl.rows[hi + 1:]:')
lines.append('        for c in row.cells:')
lines.append('            for p in c._element.findall(f".://{NS}}}p"):')
lines.append('                clear_para(p)')
lines.append('    ri = hi + 1')
lines.append('    for it in items:')
lines.append('        if ri >= len(tbl.rows):')
lines.append('            break')
lines.append('        row = tbl.rows[ri]')
lines.append('        cells = row.cells')
lines.append('        if len(cells) > 0:')
lines.append('            set_cell(cells[0], it["title"], bold=True, size=10.5)')
lines.append('        if len(cells) > 1 and it.get("role"):')
lines.append('            set_cell(cells[1], it["role"], size=9.5)')
lines.append('        if len(cells) > 2 and it.get("dates"):')
lines.append('            set_cell(cells[2], it["dates"], size=9.5)')
lines.append('        for bi, b in enumerate(it.get("bullets", [])):')
lines.append('            ci = 3 + bi')
lines.append('            if ci < len(cells):')
lines.append('                paras = cells[ci]._element.findall(f".://{NS}}}p")')
lines.append('                if paras:')
lines.append('                    clear_para(paras[0])')
lines.append('                    add_run(paras[0], "\\u2022 " + b, size=9.5)')
lines.append('        ri += 1')
lines.append('')
lines.append('')
lines.append('def update_skills(doc, d):')
lines.append('    tbl = doc.tables[-1]')
lines.append('    for row in tbl.rows:')
lines.append('        for c in row.cells:')
lines.append('            for p in c._element.findall(f".://{NS}}}p"):')
lines.append('                clear_para(p)')
lines.append('    cells = tbl.rows[0].cells')
lines.append('    for i, s in enumerate(d.get("skills", [])):')
lines.append('        if i < len(cells):')
lines.append('            paras = cells[i]._element.findall(f".://{NS}}}p")')
lines.append('            if paras:')
lines.append('                clear_para(paras[0])')
lines.append('                add_run(paras[0], "\\u2022 " + s, size=9.5)')
lines.append('')
lines.append('')
lines.append('def build(md_path, out_path, template=None):')
lines.append('    if not template:')
lines.append('        print("ERROR: --template parameter required", file=sys.stderr)')
lines.append('        sys.exit(1)')
lines.append('    if not os.path.exists(template):')
lines.append('        print("ERROR: template not found: " + template, file=sys.stderr)')
lines.append('        sys.exit(1)')
lines.append('    d = parse_md(md_path)')
lines.append('    tmp = tempfile.NamedTemporaryFile(suffix=".docx", delete=False)')
lines.append('    tmp_path = tmp.name')
lines.append('    tmp.close()')
lines.append('    shutil.copy2(template, tmp_path)')
lines.append('    print("  template: " + os.path.basename(template))')
lines.append('    doc = Document(tmp_path)')
lines.append('    update_header(doc, d)')
lines.append('    update_edu(doc, d)')
lines.append('    update_section(doc, 4, d["projects"], ["项目经历"])')
lines.append('    update_section(doc, 5, d["practices"], ["实践经历"])')
lines.append('    update_section(doc, 6, d["campus"], ["校园经历"])')
lines.append('    update_skills(doc, d)')
lines.append('    doc.save(out_path)')
lines.append('    os.unlink(tmp_path)')
lines.append('    print("  docx: " + os.path.basename(out_path))')
lines.append('    try:')
lines.append('        import win32com.client')
lines.append('        pdf_path = os.path.splitext(out_path)[0] + ".pdf"')
lines.append('        word = win32com.client.Dispatch("Word.Application")')
lines.append('        word.Visible = False')
lines.append('        word.DisplayAlerts = 0')
lines.append('        doc_src = word.Documents.Open(os.path.abspath(out_path))')
lines.append('        doc_src.SaveAs(os.path.abspath(pdf_path), FileFormat=17)')
lines.append('        doc_src.Close(SaveChanges=False)')
lines.append('        word.Quit()')
lines.append('        print("  pdf: " + os.path.basename(pdf_path))')
lines.append('    except Exception as e:')
lines.append('        print("  pdf: skipped (" + str(e) + ")")')
lines.append('    return d')
lines.append('')
lines.append('')
lines.append('if __name__ == "__main__":')
lines.append('    import argparse')
lines.append('    p = argparse.ArgumentParser(description="Resume generator with PDF export")')
lines.append('    p.add_argument("md_path", help="Path to resume markdown file")')
lines.append('    p.add_argument("out_path", help="Output docx path")')
lines.append('    p.add_argument("--template", required=True, help="Template docx path")')
lines.append('    args = p.parse_args()')
lines.append('    build(args.md_path, args.out_path, template=args.template)')

with open(r"D:\Obsidian\SCM-Career\.tools\gen_resume.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Written: " + str(len(lines)) + " lines")
