lines = []
# Helper functions
lines.append('')
lines.append('def find_text(el):')
lines.append("    return ''.join(t.text or '' for t in el.findall(f'.//{NS}}}t'))")
lines.append('')
lines.append('def clear_para(p):')
lines.append("    for t in p.findall(f'.//{NS}}}t'):")
lines.append("        t.text = ''")
lines.append('')
lines.append('def add_run(par, text, bold=False, size=10.5):')
lines.append("    r = OxmlElement('w:r')")
lines.append('    if bold:')
lines.append("        rPr = OxmlElement('w:rPr')")
lines.append("        rPr.append(OxmlElement('w:b'))")
lines.append('        r.append(rPr)')
lines.append("    t = OxmlElement('w:t')")
lines.append('    t.text = text')
lines.append("    t.set(qn('xml:space'), 'preserve')")
lines.append('    r.append(t)')
lines.append('    par.append(r)')
lines.append('')
lines.append('def set_cell(cell, text, bold=False, size=10.5):')
lines.append("    paras = cell._element.findall(f'.//{NS}}}p')")
lines.append('    if not paras:')
lines.append("        p = OxmlElement('w:p')")
lines.append('        cell._element.append(p)')
lines.append('        paras = [p]')
lines.append('    clear_para(paras[0])')
lines.append('    add_run(paras[0], text, bold=bold, size=size)')
lines.append('')

path = r'D:\Obsidian\SCM-Career\.tools\gen_resume.py'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f'Part 2 written: {len(lines)} lines')
