lines = []
lines.append('')
lines.append('def parse_md(path):')
lines.append("    with open(path, encoding='utf-8') as f:")
lines.append('        text = f.read()')
lines.append("    d = dict(name='', contact='', intent='', summary='',")
lines.append("             edu_school='', edu_major='', edu_degree='', edu_dates='',")
lines.append("             courses='', honors='',")
lines.append("             projects=[], practices=[], campus=[], skills=[])")
lines.append('    section = None')
lines.append('    item = None')
lines.append("    for line in text.split('\\\\n'):")
lines.append('        s = line.strip()')
lines.append('        if not s: continue')
lines.append("        if s.startswith('# '):")
lines.append("            d['name'] = s[2:].strip()")
lines.append("        elif '\\\\u2016' in s and not s.startswith('**') and not d['contact']:")
lines.append("            d['contact'] = s")
lines.append("        elif re.match(r'^\\\\*\\\\*\\\\u6c42\\\\u804c\\\\u610f\\\\u5411[：:]\\\\*\\\\*', s):")
lines.append("            d['intent'] = re.sub(r'\\\\*\\\\*\\\\u6c42\\\\u804c\\\\u610f\\\\u5411[：:]\\\\*\\\\*', '', s).strip()")
lines.append("        elif re.match(r'^\\\\*\\\\*\\\\u4e2a\\\\u4eba\\\\u4f18\\\\u52bf[：:]\\\\*\\\\*', s):")
lines.append("            d['summary'] = re.sub(r'\\\\*\\\\*\\\\u4e2a\\\\u4eba\\\\u4f18\\\\u52bf[：:]\\\\*\\\\*', '', s).strip()")
lines.append("        elif s == '## \\\\u6559\\\\u80b2\\\\u80cc\\\\u666f': section = 'edu'")
lines.append("        elif s == '## \\\\u9879\\\\u76ee\\\\u7ecf\\\\u5386': section = 'projects'")
lines.append("        elif s == '## \\\\u5b9e\\\\u8df5\\\\u7ecf\\\\u5386': section = 'practices'")
lines.append("        elif s == '## \\\\u6821\\\\u56ed\\\\u7ecf\\\\u5386': section = 'campus'")
lines.append("        elif s == '## \\\\u7efc\\\\u5408\\\\u6280\\\\u80fd': section = 'skills'")
lines.append("        elif section == 'edu':")
lines.append("            m = re.match(r'\\\\*\\\\*([^*]+)\\\\*\\\\*\\\\s*[\\\\u2016|]\\\\s*([^*]+)\\\\s*[\\\\u2016|]\\\\s*([^*]+)\\\\s*[\\\\u2016|]\\\\s*([^*]+)\\\\*\\\\*', s)")
lines.append('            if m:')
lines.append("                d['edu_school'], d['edu_major'], d['edu_degree'], d['edu_dates'] = m.group(1).strip(), m.group(2).strip(), m.group(3).strip(), m.group(4).replace('**','').strip()")
lines.append("            elif '\\\\u6838\\\\u5fc3\\\\u8bfe\\\\u7a0b' in s:")
lines.append("                d['courses'] = re.sub(r'\\\\*\\\\*\\\\u6838\\\\u5fc3\\\\u8bfe\\\\u7a0b[：:]\\\\*\\\\*', '', s).strip()")
lines.append("            elif '\\\\u8363\\\\u8a89\\\\u5956\\\\u52b1' in s:")
lines.append("                d['honors'] = re.sub(r'\\\\*\\\\*\\\\u8363\\\\u8a89\\\\u5956\\\\u52b1[：:]\\\\*\\\\*', '', s).strip()")
lines.append("        elif s.startswith('### '):")
lines.append("            if section in ('projects','practices','campus'):")
lines.append("                item = dict(title=s[4:].strip(), role='', dates='', bullets=[])")
lines.append("                d[section].append(item)")
lines.append("        elif s.startswith('**') and ('\\\\u2016' in s or '|' in s) and item is not None:")
lines.append("            parts = re.split(r'\\\\*\\\\*[^*]+\\\\*\\\\*\\\\s*[\\\\u2016|]\\\\s*', s, maxsplit=1)")
lines.append("            if len(parts) >= 2:")
lines.append("                item['role'] = parts[0].replace('**','').strip()")
lines.append("                item['dates'] = parts[1].replace('**','').strip()")
lines.append("        elif s.startswith('- ') and item is not None:")
lines.append("            item['bullets'].append(s[2:].strip())")
lines.append("        elif section == 'skills' and s.startswith('- '):")
lines.append("            d['skills'].append(s[2:].strip())")
lines.append('    return d')
lines.append('')

path = r'D:\Obsidian\SCM-Career\.tools\gen_resume.py'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f'Part 3 written: {len(lines)} lines')
